### ISSUE TITLE
New models?

### ISSUE THREAD

**Issue by R4ZZ3** [TurkuNLP/FinBERT#4]
Hi,

I would just like to now what your current plans are for future development?
Are you going to keep training applicable new models from the latest research that you have resources for. Personally I am most curious whether you could train ALBERT and see if it improves performance.

**Comment by fginter** [comment]
This might eventually get done, but training a number of different xxxERTxxx models  is not very high on our priority list. The performance differences between these various BERT derivatives are not exactly huge, and not necessarily worth the non-trivial effort needed to train them successfully, especially considering our constrained resources which we must allocate wisely. We might try for a GPT, though, since there is no good text generation model for Finnish, so that would give us most bang for our buck. That's a plan, rather than a firm promise, though. :wink:
